import './globals.css'
import { Inter } from 'next/font/google'

export const metadata = {
  title: 'Trello 2.0 - GPT-4 AI',
  description: 'Generated by Steven, inspired by Sonny Sangha',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='bg-[#F5F6F8]'>{children}</body>
    </html>
  )
}
